const http = require('node:http');
const fs = require('node:fs');
const path = require('node:path');
const crypto = require('node:crypto');
const { spawn } = require('node:child_process');
const bcrypt = require('bcryptjs');
const { migrate, query: dbQuery } = require('./db');

const PORT = Number(process.env.PORT || 3000), HOST = process.env.HOST || '0.0.0.0';
const DATA_DIR = process.env.DATA_DIR || path.join(__dirname, 'data');
const BACKUP_DIR = process.env.BACKUP_DIR || path.join(DATA_DIR, 'backups');
const COOKIE = 'vault_session', MAX_BODY = 1024 * 1024;
const secureCookie = process.env.COOKIE_SECURE ? process.env.COOKIE_SECURE === 'true' : process.env.NODE_ENV === 'production';
const storageMode = (process.env.BACKUP_STORAGE || 'local').toLowerCase();
const sessions = new Map(), jobs = new Map(), loginAttempts = new Map();
let jobRunning = false;
let projectId;
for (const dir of [DATA_DIR, BACKUP_DIR]) fs.mkdirSync(dir, { recursive: true, mode: 0o700 });
for (const key of ['ADMIN_USERNAME', 'APP_ENCRYPTION_KEY']) if (!process.env[key]) throw new Error(`${key} is required`);
if (!process.env.ADMIN_PASSWORD_HASH && !process.env.ADMIN_PASSWORD_HASH_B64) throw new Error('ADMIN_PASSWORD_HASH_B64 is required');
if (!['local', 's3'].includes(storageMode)) throw new Error('BACKUP_STORAGE must be local or s3');
if (storageMode === 's3' && (!process.env.S3_BUCKET || !process.env.S3_REGION)) throw new Error('S3_BUCKET and S3_REGION are required for S3 storage');
const encryptionKey = crypto.createHash('sha256').update(process.env.APP_ENCRYPTION_KEY).digest();

function readJson(file, fallback) { try { return JSON.parse(fs.readFileSync(file, 'utf8')); } catch { return fallback; } }
function writeJson(file, value) { const tmp = `${file}.tmp`; fs.writeFileSync(tmp, JSON.stringify(value, null, 2), { mode: 0o600 }); fs.renameSync(tmp, file); }
function vault() { const v = readJson(path.join(DATA_DIR, 'vault.json'), { targets: [] }); return Array.isArray(v.targets) ? v : { targets: [] }; }
function history() { const h = readJson(path.join(DATA_DIR, 'history.json'), []); return Array.isArray(h) ? h : []; }
function saveHistory(entry) { const h = history().filter(x => x.id !== entry.id); h.push(entry); writeJson(path.join(DATA_DIR, 'history.json'), h.slice(-500)); }
function encrypt(value) { const iv = crypto.randomBytes(12), c = crypto.createCipheriv('aes-256-gcm', encryptionKey, iv); const data = Buffer.concat([c.update(value, 'utf8'), c.final()]); return [iv, c.getAuthTag(), data].map(x => x.toString('base64')).join('.'); }
function decrypt(value) { const [iv, tag, data] = value.split('.'), d = crypto.createDecipheriv('aes-256-gcm', encryptionKey, Buffer.from(iv, 'base64')); d.setAuthTag(Buffer.from(tag, 'base64')); return Buffer.concat([d.update(Buffer.from(data, 'base64')), d.final()]).toString('utf8'); }
function verifyPassword(password) { const stored = process.env.ADMIN_PASSWORD_HASH_B64 ? Buffer.from(process.env.ADMIN_PASSWORD_HASH_B64, 'base64').toString('utf8') : String(process.env.ADMIN_PASSWORD_HASH); if (/^\$2[aby]?\$\d{2}\$/.test(stored)) return bcrypt.compareSync(password, stored); const separator = stored.includes(':') ? ':' : '$', [salt, digest] = stored.split(separator); if (!salt || !/^[a-f0-9]{128}$/i.test(digest)) return false; const actual = crypto.scryptSync(password, salt, 64).toString('hex'); return crypto.timingSafeEqual(Buffer.from(actual, 'hex'), Buffer.from(digest, 'hex')); }
function parseCookies(req) { return Object.fromEntries((req.headers.cookie || '').split(';').filter(Boolean).map(x => { const i = x.indexOf('='); return [x.slice(0, i).trim(), decodeURIComponent(x.slice(i + 1))]; })); }
function auth(req) { const token = parseCookies(req).vault_session, s = token && sessions.get(token); return s && s.expires > Date.now() ? { token, ...s } : null; }
function send(res, status, value, headers = {}) { res.writeHead(status, { 'Content-Type': 'application/json; charset=utf-8', 'Cache-Control': 'no-store', ...headers }); res.end(JSON.stringify(value)); }
function staticFile(res, name, type) { const content = fs.readFileSync(path.join(__dirname, 'public', name)); res.writeHead(200, { 'Content-Type': type, 'Cache-Control': 'no-store' }); res.end(content); }
function readBody(req) { return new Promise((resolve, reject) => { let raw = ''; req.on('data', c => { raw += c; if (raw.length > MAX_BODY) { reject(new Error('Request too large')); req.destroy(); } }); req.on('end', () => { try { resolve(raw ? JSON.parse(raw) : {}); } catch { reject(new Error('Invalid JSON')); } }); req.on('error', reject); }); }
function validName(v) { return typeof v === 'string' && /^[A-Za-z0-9_-]{1,48}$/.test(v); }
function validUrl(v) { try { const u = new URL(v); return ['postgres:', 'postgresql:'].includes(u.protocol) && u.hostname && u.pathname.length > 1; } catch { return false; } }
function safeFolder(v) { return typeof v === 'string' && /^[0-9TZ_.-]{10,64}$/.test(v); }
function csrf(req, session) { try { return req.headers['x-csrf-token'] === session.csrf && req.headers.origin && new URL(req.headers.origin).host === req.headers.host; } catch { return false; } }
function redacted(text) { return String(text).replace(/postgres(?:ql)?:\/\/[^\s]+/gi, '[redacted-url]'); }
function command(bin, args, job, cwd) { return new Promise((resolve, reject) => { const env = { ...process.env }; delete env.PGPASSWORD; const child = spawn(bin, args, { cwd, env, stdio: ['ignore', 'pipe', 'pipe'] }); let stderr = ''; child.stdout.on('data', d => job.log += redacted(d)); child.stderr.on('data', d => { stderr += d; job.log += redacted(d); }); child.on('error', reject); child.on('close', code => code === 0 ? resolve() : reject(new Error(`${bin} exited with code ${code}: ${redacted(stderr).slice(-500)}`))); }); }
function capture(bin, args, cwd) { return new Promise((resolve, reject) => { const child = spawn(bin, args, { cwd, env: process.env, stdio: ['ignore', 'pipe', 'pipe'] }); let out = '', err = ''; child.stdout.on('data', d => out += d); child.stderr.on('data', d => err += d); child.on('error', reject); child.on('close', code => code === 0 ? resolve(out) : reject(new Error(`${bin} exited with code ${code}: ${err.slice(-300)}`))); }); }
async function archiveFolder(name) { const archive = path.join(DATA_DIR, `${name}.tar.gz`); await command('tar', ['-czf', archive, '-C', BACKUP_DIR, name], { log: '' }, DATA_DIR); return archive; }
async function uploadS3(archive, name) { const key = `${process.env.S3_PREFIX || 'vaultmanager'}/${name}.tar.gz`; await command('aws', ['s3', 'cp', archive, `s3://${process.env.S3_BUCKET}/${key}`, '--region', process.env.S3_REGION, '--only-show-errors'], { log: '' }, DATA_DIR); return key; }
async function signS3(key) { return (await capture('aws', ['s3', 'presign', `s3://${process.env.S3_BUCKET}/${key}`, '--region', process.env.S3_REGION, '--expires-in', '900'], DATA_DIR)).trim(); }
async function bootstrapProject() { const existing = await dbQuery('SELECT id FROM projects WHERE name=$1 LIMIT 1', ['Default Project']); if (existing.rowCount) { projectId = existing.rows[0].id; } else { projectId = crypto.randomUUID(); await dbQuery('INSERT INTO projects(id,name) VALUES($1,$2)', [projectId, 'Default Project']); } const count = await dbQuery('SELECT count(*)::int AS count FROM database_targets WHERE project_id=$1', [projectId]); if (count.rows[0].count === 0) for (const t of vault().targets) await dbQuery('INSERT INTO database_targets(id,project_id,name,connection_encrypted) VALUES($1,$2,$3,$4) ON CONFLICT (id) DO NOTHING', [t.id, projectId, t.name, t.connection]); const targets = await dbQuery('SELECT id,name FROM database_targets WHERE project_id=$1', [projectId]); for (const t of targets.rows) await dbQuery('INSERT INTO backup_jobs(id,project_id,database_target_id,name,schedule) SELECT $1,$2,$3,$4,$5 WHERE NOT EXISTS (SELECT 1 FROM backup_jobs WHERE database_target_id=$3)', [crypto.randomUUID(), projectId, t.id, `${t.name} Backup`, process.env.BACKUP_CRON || null]); const storage = await dbQuery('SELECT count(*)::int AS count FROM storage_destinations WHERE project_id=$1', [projectId]); if (storage.rows[0].count === 0) { await dbQuery('INSERT INTO storage_destinations(id,project_id,name,provider,path,enabled) VALUES($1,$2,$3,$4,$5,true)', [crypto.randomUUID(), projectId, 'Local storage', 'local', BACKUP_DIR]); if (storageMode === 's3') await dbQuery('INSERT INTO storage_destinations(id,project_id,name,provider,region,bucket,prefix,credentials_encrypted,enabled) VALUES($1,$2,$3,$4,$5,$6,$7,$8,true)', [crypto.randomUUID(), projectId, 'S3 storage', 's3', process.env.S3_REGION, process.env.S3_BUCKET, process.env.S3_PREFIX || 'vaultmanager', encrypt(JSON.stringify({ accessKeyId: process.env.AWS_ACCESS_KEY_ID || '', secretAccessKey: process.env.AWS_SECRET_ACCESS_KEY || '', sessionToken: process.env.AWS_SESSION_TOKEN || '' }))]); } }
async function dbTargets() { return (await dbQuery('SELECT id,name,status,last_connection_test_at AS "lastConnectionTestAt",created_at AS "createdAt" FROM database_targets WHERE project_id=$1 ORDER BY created_at', [projectId])).rows; }
async function publicTargets() { return dbTargets(); }
async function createRun(job) { await dbQuery('INSERT INTO backup_runs(id,backup_job_id,project_id,database_target_id,status,triggered_by,started_at) VALUES($1,$2,$3,$4,$5,$6,now()) ON CONFLICT (id) DO NOTHING', [job.id, job.jobId || null, projectId, job.targetId, 'queued', job.scheduled ? 'scheduler' : 'admin']); }
async function updateRun(job) { await dbQuery('UPDATE backup_runs SET status=$2,completed_at=CASE WHEN $2 IN (\'succeeded\',\'failed\') THEN now() ELSE completed_at END,error_message=$3 WHERE id=$1', [job.id, job.status, job.error || null]); }
async function persistLog(job, phase, message, level = 'info') { await dbQuery('INSERT INTO backup_logs(backup_run_id,level,phase,message) VALUES($1,$2,$3,$4)', [job.id, level, phase, message]); }
async function audit(action, resourceType, resourceId = null, metadata = {}) { await dbQuery('INSERT INTO audit_logs(project_id,actor,action,resource_type,resource_id,metadata) VALUES($1,$2,$3,$4,$5,$6)', [projectId, process.env.ADMIN_USERNAME, action, resourceType, resourceId, JSON.stringify(metadata)]); }
async function runBackup(target, job) { const name = new Date().toISOString().replace(/[:.]/g, '-'); const folder = path.join(BACKUP_DIR, name); fs.mkdirSync(folder, { recursive: true, mode: 0o700 }); job.folder = name; for (const [label, args] of [['roles.sql', ['db', 'dump', '--db-url', target.url, '-f', 'roles.sql', '--role-only']], ['schema.sql', ['db', 'dump', '--db-url', target.url, '-f', 'schema.sql']], ['data.sql', ['db', 'dump', '--db-url', target.url, '-f', 'data.sql', '--data-only', '--use-copy']]]) { job.log += `Running ${label}...\n`; await persistLog(job, label.replace('.sql', ''), `Starting ${label}`); await command('supabase', args, job, folder); await persistLog(job, label.replace('.sql', ''), `${label} completed`); } await persistLog(job, 'packaging', 'Creating backup archive'); const archive = await archiveFolder(name); if (storageMode === 's3') { await persistLog(job, 'upload', 'Uploading archive to S3'); job.storageKey = await uploadS3(archive, name); fs.rmSync(archive, { force: true }); } job.status = 'succeeded'; job.finishedAt = new Date().toISOString(); saveHistory({ id: job.id, type: 'backup', targetId: job.targetId, folder: name, status: job.status, startedAt: job.startedAt, finishedAt: job.finishedAt, storage: storageMode, storageKey: job.storageKey || null }); }
async function runRestore(target, job) { let folder = path.join(BACKUP_DIR, job.folder); if (!fs.existsSync(folder) && storageMode === 's3') { const source = history().find(x => x.folder === job.folder && x.type === 'backup' && x.storageKey); if (!source) throw new Error('Backup folder not found'); const archive = path.join(DATA_DIR, `${job.folder}.tar.gz`); await command('aws', ['s3', 'cp', `s3://${process.env.S3_BUCKET}/${source.storageKey}`, archive, '--only-show-errors'], job, DATA_DIR); await command('tar', ['-xzf', archive, '-C', BACKUP_DIR], job, DATA_DIR); fs.rmSync(archive, { force: true }); } if (!fs.existsSync(folder)) throw new Error('Backup folder not found'); for (const [label, args] of [['roles.sql', ['-v', 'ON_ERROR_STOP=1', '--single-transaction', target.url, '-f', 'roles.sql']], ['schema.sql', ['-v', 'ON_ERROR_STOP=1', '--single-transaction', target.url, '-f', 'schema.sql']], ['data.sql', ['-v', 'ON_ERROR_STOP=1', '--single-transaction', target.url, '-c', "SET session_replication_role = 'replica';", '-f', 'data.sql']]]) { job.log += `Restoring ${label}...\n`; await command('psql', args, job, folder); } job.status = 'succeeded'; job.finishedAt = new Date().toISOString(); saveHistory({ id: job.id, type: 'restore', targetId: job.targetId, folder: job.folder, status: job.status, startedAt: job.startedAt, finishedAt: job.finishedAt, storage: storageMode }); }
function startJob(job, target) { jobs.set(job.id, job); (async () => { try { await createRun(job); if (job.type === 'restore') await dbQuery('INSERT INTO restore_jobs(id,backup_run_id,destination_target_id,status,initiated_by,started_at) VALUES($1,$2,$3,$4,$5,now())', [crypto.randomUUID(), job.id, job.targetId, 'running', process.env.ADMIN_USERNAME]); await audit(job.type === 'backup' ? 'backup.queued' : 'restore.started', job.type, job.id, { targetId: job.targetId }); if (job.type === 'backup') { job.status = 'queued'; job.log = `Queued backup job ${job.id}\n`; return; } while (jobRunning) await new Promise(r => setTimeout(r, 500)); jobRunning = true; job.status = 'running'; job.log = `Started restore job ${job.id}\n`; await updateRun(job); try { await runRestore(target, job); job.log += 'restore completed successfully.\n'; await audit('restore.completed', 'restore', job.id); } catch (e) { job.status = 'failed'; job.error = e.message; job.finishedAt = new Date().toISOString(); job.log += `FAILED: ${e.message}\n`; await persistLog(job, 'error', e.message, 'error'); await audit('restore.failed', 'restore', job.id, { error: e.message }); } await updateRun(job); } catch (e) { job.status = 'failed'; job.error = e.message; console.error('Job persistence failed:', e); } finally { jobRunning = false; } })(); }
function cronFieldMatches(field, value, min, max) { return field.split(',').some(part => { const [range, stepText] = part.split('/'), step = Number(stepText || 1); if (!Number.isInteger(step) || step < 1) return false; if (range === '*') return value >= min && value <= max && (value - min) % step === 0; const [a, b = a] = range.split('-').map(Number); return Number.isInteger(a) && Number.isInteger(b) && a >= min && b <= max && value >= a && value <= b && (value - a) % step === 0; }); }
function cronMatches(date, expression) { const p = String(expression || '').trim().split(/\s+/), v = [date.getMinutes(), date.getHours(), date.getDate(), date.getMonth() + 1, date.getDay()], ranges = [[0, 59], [0, 23], [1, 31], [1, 12], [0, 6]]; return p.length === 5 && p.every((x, i) => cronFieldMatches(x, v[i], ...ranges[i])); }
async function cronTick() { if (!projectId || !process.env.BACKUP_CRON || !process.env.CRON_TARGET_ID || !cronMatches(new Date(), process.env.BACKUP_CRON) || [...jobs.values()].some(j => j.scheduled && j.status === 'running')) return; const result = await dbQuery('SELECT t.id,t.connection_encrypted,j.id AS job_id FROM database_targets t LEFT JOIN backup_jobs j ON j.database_target_id=t.id WHERE t.id=$1 AND t.project_id=$2', [process.env.CRON_TARGET_ID, projectId]); const t = result.rows[0]; if (!t) return console.error('CRON_TARGET_ID does not match a target'); startJob({ id: crypto.randomUUID(), jobId: t.job_id, type: 'backup', targetId: t.id, status: 'queued', startedAt: new Date().toISOString(), scheduled: true }, { url: decrypt(t.connection_encrypted) }); }
// Scheduled jobs are claimed by the worker from PostgreSQL. Keeping scheduling out of
// the web process prevents duplicate runs when Coolify scales or restarts the UI.

const originalStartJob = startJob;
startJob = (job, target) => { if (job.type !== 'restore') return originalStartJob(job, target); jobs.set(job.id, job); (async () => { try { await createRun(job); await dbQuery('INSERT INTO restore_jobs(id,backup_run_id,destination_target_id,status,initiated_by,backup_folder) VALUES($1,$2,$3,$4,$5,$6)', [crypto.randomUUID(), job.id, job.targetId, 'queued', process.env.ADMIN_USERNAME, job.folder]); await audit('restore.queued', 'restore', job.id, { targetId: job.targetId, folder: job.folder }); job.status = 'queued'; job.log = `Queued restore job ${job.id}\n`; } catch (e) { job.status = 'failed'; job.error = e.message; console.error('Restore queue persistence failed:', e); } })(); };

const server = http.createServer(async (req, res) => { try {
  if (req.method === 'GET' && req.url === '/api/system/health') { try { await dbQuery('SELECT 1'); const worker = await dbQuery("SELECT count(*)::int AS count FROM worker_heartbeats WHERE last_seen_at > now() - interval '45 seconds'"); return send(res, worker.rows[0].count > 0 ? 200 : 503, { application: 'healthy', database: 'healthy', worker: worker.rows[0].count > 0 ? 'healthy' : 'unavailable', storage: storageMode, scheduler: 'worker' }); } catch { return send(res, 503, { application: 'healthy', database: 'unavailable', worker: 'unknown' }); } }
  if (req.method === 'GET' && req.url === '/') return staticFile(res, 'index.html', 'text/html; charset=utf-8');
  if (req.method === 'GET' && req.url === '/app.js') return staticFile(res, 'app.js', 'application/javascript');
  if (req.method === 'GET' && req.url === '/styles.css') return staticFile(res, 'styles.css', 'text/css');
  if (req.method === 'GET' && req.url === '/api/system/health') { try { await dbQuery('SELECT 1'); return send(res, 200, { application: 'healthy', database: 'healthy', worker: jobRunning ? 'running' : 'idle', storage: storageMode, scheduler: process.env.BACKUP_CRON ? 'configured' : 'disabled' }); } catch { return send(res, 503, { application: 'healthy', database: 'unavailable' }); } }
  if (req.method === 'POST' && req.url === '/api/login') { const ip = req.socket.remoteAddress || 'unknown', a = loginAttempts.get(ip) || { count: 0, reset: Date.now() + 60000 }; if (a.reset < Date.now()) { a.count = 0; a.reset = Date.now() + 60000; } if (a.count >= 10) return send(res, 429, { error: 'Too many attempts. Try again shortly.' }); const b = await readBody(req); if (b.username !== process.env.ADMIN_USERNAME || !verifyPassword(b.password || '')) { a.count++; loginAttempts.set(ip, a); return send(res, 401, { error: 'Invalid credentials' }); } const token = crypto.randomBytes(32).toString('hex'); sessions.set(token, { csrf: crypto.randomBytes(24).toString('hex'), expires: Date.now() + 8 * 3600e3 }); return send(res, 200, { ok: true }, { 'Set-Cookie': `${COOKIE}=${token}; HttpOnly; ${secureCookie ? 'Secure; ' : ''}SameSite=Strict; Path=/; Max-Age=28800` }); }
  const session = auth(req); if (!session) return send(res, 401, { error: 'Authentication required' });
  if (req.method === 'POST' && req.url === '/api/logout') { sessions.delete(session.token); return send(res, 200, { ok: true }, { 'Set-Cookie': `${COOKIE}=; HttpOnly; ${secureCookie ? 'Secure; ' : ''}SameSite=Strict; Path=/; Max-Age=0` }); }
  if (req.method === 'GET' && req.url === '/api/session') { const runs = await dbQuery('SELECT r.id,r.status,r.triggered_by AS "triggeredBy",r.started_at AS "startedAt",r.completed_at AS "completedAt",r.error_message AS error,j.name AS "jobName",t.name AS "targetName" FROM backup_runs r LEFT JOIN backup_jobs j ON j.id=r.backup_job_id LEFT JOIN database_targets t ON t.id=r.database_target_id WHERE r.project_id=$1 ORDER BY r.created_at DESC LIMIT 50', [projectId]); const backupJobs = await dbQuery('SELECT j.id,j.name,j.enabled,j.schedule,j.timezone,j.last_run_at AS "lastRunAt",j.next_run_at AS "nextRunAt",t.id AS "targetId",t.name AS "targetName" FROM backup_jobs j JOIN database_targets t ON t.id=j.database_target_id WHERE j.project_id=$1 ORDER BY j.created_at', [projectId]); return send(res, 200, { username: process.env.ADMIN_USERNAME, csrf: session.csrf, targets: await publicTargets(), jobs: [...jobs.values()].slice(-50), backupJobs: backupJobs.rows, runs: runs.rows, history: history().slice(-50).reverse(), storage: storageMode, cron: process.env.BACKUP_CRON || null }); }
  if (req.method === 'GET' && req.url === '/api/backups') { const backups = await dbQuery('SELECT r.id,r.status,r.backup_folder AS folder,r.storage_key AS "storageKey",r.started_at AS "startedAt",r.completed_at AS "completedAt",r.total_size_bytes AS "totalSizeBytes",r.checksum,r.error_message AS error,t.name AS "targetName" FROM backup_runs r JOIN database_targets t ON t.id=r.database_target_id WHERE r.project_id=$1 ORDER BY r.created_at DESC LIMIT 100', [projectId]); return send(res, 200, { backups: backups.rows }); }
  if (req.method === 'GET' && req.url === '/api/storage') { const storage = await dbQuery('SELECT id,name,provider,endpoint,region,bucket,prefix,path,enabled,created_at AS "createdAt" FROM storage_destinations WHERE project_id=$1 ORDER BY created_at', [projectId]); return send(res, 200, { storage: storage.rows }); }
  if (req.method === 'GET' && req.url === '/api/audit-logs') { const result = await dbQuery('SELECT created_at AS "createdAt",actor,action,resource_type AS "resourceType",resource_id AS "resourceId",metadata FROM audit_logs WHERE project_id=$1 ORDER BY created_at DESC LIMIT 100', [projectId]); return send(res, 200, { auditLogs: result.rows }); }
  if (req.method === 'GET' && req.url === '/api/settings') { const result = await dbQuery("SELECT key,value,updated_at AS \"updatedAt\" FROM app_settings WHERE key IN ('timezone','logRetentionDays','defaultRetentionCount','maxConcurrentJobs','notificationsEnabled') ORDER BY key"); return send(res, 200, { settings: result.rows }); }
  if (req.method === 'GET' && req.url.startsWith('/api/backup-runs/') && !req.url.endsWith('/logs')) { const runId = req.url.split('/')[3], run = await dbQuery('SELECT id,status,started_at AS "startedAt",completed_at AS "completedAt",total_size_bytes AS "totalSizeBytes",checksum,error_message AS error FROM backup_runs WHERE id=$1 AND project_id=$2', [runId, projectId]); return run.rowCount ? send(res, 200, { run: run.rows[0] }) : send(res, 404, { error: 'Run not found' }); }
  if (req.method === 'GET' && req.url.startsWith('/api/backup-runs/') && req.url.endsWith('/logs')) { const runId = req.url.split('/')[3]; const logs = await dbQuery('SELECT l.logged_at AS timestamp,l.level,l.phase,l.message FROM backup_logs l JOIN backup_runs r ON r.id=l.backup_run_id WHERE l.backup_run_id=$1 AND r.project_id=$2 ORDER BY l.logged_at', [runId, projectId]); return send(res, 200, { logs: logs.rows }); }
  if (req.method === 'GET' && req.url.startsWith('/api/backups/') && req.url.endsWith('/download')) { const name = req.url.split('/')[3]; if (!safeFolder(name)) return send(res, 400, { error: 'Invalid backup name' }); const result = await dbQuery('SELECT storage_key AS "storageKey" FROM backup_runs WHERE backup_folder=$1 AND project_id=$2 AND status=\'succeeded\' LIMIT 1', [name, projectId]); if (!result.rowCount) return send(res, 404, { error: 'Backup not found' }); if (storageMode === 's3' && result.rows[0].storageKey) return res.writeHead(302, { Location: await signS3(result.rows[0].storageKey) }).end(); const archive = await archiveFolder(name); res.writeHead(200, { 'Content-Type': 'application/gzip', 'Content-Disposition': `attachment; filename="${name}.tar.gz"`, 'Content-Length': fs.statSync(archive).size }); fs.createReadStream(archive).pipe(res).on('finish', () => fs.rmSync(archive, { force: true })); return; }
  if (!csrf(req, session)) return send(res, 403, { error: 'CSRF validation failed' });
  if (req.method === 'POST' && req.url.startsWith('/api/targets/') && req.url.endsWith('/test')) { const id = req.url.split('/')[3], target = await dbQuery('SELECT id,connection_encrypted FROM database_targets WHERE id=$1 AND project_id=$2', [id, projectId]); if (!target.rowCount) return send(res, 404, { error: 'Target not found' }); const job = { log: '' }; try { await command('psql', ['-v', 'ON_ERROR_STOP=1', '-X', decrypt(target.rows[0].connection_encrypted), '-c', 'SELECT 1'], job, DATA_DIR); await dbQuery("UPDATE database_targets SET status='healthy',last_connection_test_at=now(),updated_at=now() WHERE id=$1", [id]); await audit('target.connection_tested', 'target', id, { status: 'healthy' }); return send(res, 200, { status: 'healthy' }); } catch (e) { await dbQuery("UPDATE database_targets SET status='unhealthy',last_connection_test_at=now(),updated_at=now() WHERE id=$1", [id]); await audit('target.connection_tested', 'target', id, { status: 'unhealthy' }); return send(res, 502, { status: 'unhealthy', error: 'Target connection test failed' }); } }
  if (req.method === 'PUT' && req.url === '/api/settings') { const b = await readBody(req), allowed = new Set(['timezone', 'logRetentionDays', 'defaultRetentionCount', 'maxConcurrentJobs', 'notificationsEnabled']), entries = Object.entries(b).filter(([key]) => allowed.has(key)); for (const [key, value] of entries) await dbQuery('INSERT INTO app_settings(key,value) VALUES($1,$2) ON CONFLICT(key) DO UPDATE SET value=$2,updated_at=now()', [key, JSON.stringify(value)]); await audit('settings.updated', 'settings', null, { keys: entries.map(([key]) => key) }); return send(res, 200, { ok: true }); }
  if (req.method === 'POST' && req.url.startsWith('/api/backup-runs/') && req.url.endsWith('/cancel')) { const runId = req.url.split('/')[3]; const result = await dbQuery('UPDATE backup_runs SET cancel_requested=true,status=CASE WHEN status=\'queued\' THEN \'cancelled\' ELSE status END WHERE id=$1 AND project_id=$2 AND status IN (\'queued\',\'running\') RETURNING id,status', [runId, projectId]); return result.rowCount ? send(res, 200, { run: result.rows[0] }) : send(res, 409, { error: 'Run cannot be cancelled' }); }
  if (req.method === 'POST' && req.url.startsWith('/api/backup-runs/') && req.url.endsWith('/retry')) { const runId = req.url.split('/')[3], result = await dbQuery('SELECT r.database_target_id,r.backup_job_id,t.connection_encrypted FROM backup_runs r JOIN database_targets t ON t.id=r.database_target_id WHERE r.id=$1 AND r.project_id=$2 AND r.status=\'failed\'', [runId, projectId]); if (!result.rowCount) return send(res, 409, { error: 'Only failed runs can be retried' }); const source = result.rows[0], job = { id: crypto.randomUUID(), jobId: source.backup_job_id, type: 'backup', targetId: source.database_target_id, status: 'queued', startedAt: new Date().toISOString(), retryOf: runId }; startJob(job, { url: decrypt(source.connection_encrypted) }); return send(res, 202, { job }); }
  if (req.method === 'POST' && req.url === '/api/targets') { const b = await readBody(req); if (!validName(b.name) || !validUrl(b.connectionString)) return send(res, 400, { error: 'Use a simple name and a valid PostgreSQL URL ending in /postgres.' }); const id = crypto.randomUUID(), jobId = crypto.randomUUID(); await dbQuery('INSERT INTO database_targets(id,project_id,name,connection_encrypted) VALUES($1,$2,$3,$4)', [id, projectId, b.name, encrypt(b.connectionString)]); await dbQuery('INSERT INTO backup_jobs(id,project_id,database_target_id,name,schedule) VALUES($1,$2,$3,$4,$5)', [jobId, projectId, id, `${b.name} Backup`, null]); return send(res, 201, { targets: await publicTargets() }); }
  if (req.method === 'POST' && req.url === '/api/storage') { const b = await readBody(req); if (!validName(b.name) || !['local', 's3'].includes(b.provider)) return send(res, 400, { error: 'Use a valid storage name and provider.' }); if (b.provider === 's3' && (!b.bucket || !b.region)) return send(res, 400, { error: 'S3 storage requires region and bucket.' }); const credentials = b.provider === 's3' ? encrypt(JSON.stringify({ accessKeyId: b.accessKeyId || '', secretAccessKey: b.secretAccessKey || '', sessionToken: b.sessionToken || '' })) : null; await dbQuery('INSERT INTO storage_destinations(id,project_id,name,provider,endpoint,region,bucket,prefix,path,credentials_encrypted) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)', [crypto.randomUUID(), projectId, b.name, b.provider, b.endpoint || null, b.region || null, b.bucket || null, b.prefix || 'vaultmanager', b.path || BACKUP_DIR, credentials]); await dbQuery('INSERT INTO audit_logs(project_id,actor,action,resource_type,metadata) VALUES($1,$2,$3,$4,$5)', [projectId, process.env.ADMIN_USERNAME, 'storage.created', 'storage', JSON.stringify({ name: b.name, provider: b.provider })]); return send(res, 201, { storage: true }); }
  if (req.method === 'DELETE' && req.url.startsWith('/api/storage/')) { const id = req.url.split('/').pop(); const result = await dbQuery('DELETE FROM storage_destinations WHERE id=$1 AND project_id=$2 RETURNING name,provider', [id, projectId]); if (!result.rowCount) return send(res, 404, { error: 'Storage destination not found' }); await audit('storage.deleted', 'storage', id, { name: result.rows[0].name, provider: result.rows[0].provider }); return send(res, 200, { ok: true }); }
  if (req.method === 'DELETE' && req.url.startsWith('/api/targets/')) { const id = req.url.split('/').pop(); await dbQuery('DELETE FROM database_targets WHERE id=$1 AND project_id=$2', [id, projectId]); return send(res, 200, { targets: await publicTargets() }); }
  if (req.method === 'POST' && (req.url.startsWith('/api/backup/') || req.url === '/api/restore')) { const b = await readBody(req), targetId = b.targetId || req.url.split('/').pop(), result = await dbQuery('SELECT t.id,t.connection_encrypted,j.id AS job_id FROM database_targets t LEFT JOIN backup_jobs j ON j.database_target_id=t.id WHERE t.id=$1 AND t.project_id=$2', [targetId, projectId]), t = result.rows[0], type = req.url === '/api/restore' ? 'restore' : 'backup'; if (!t) return send(res, 404, { error: 'Target not found' }); if (type === 'restore' && (!safeFolder(b.folder) || b.confirm !== 'RESTORE')) return send(res, 400, { error: 'Enter a valid backup folder and type RESTORE to confirm.' }); const job = { id: crypto.randomUUID(), jobId: t.job_id, type, targetId: t.id, status: 'queued', startedAt: new Date().toISOString(), ...(type === 'restore' ? { folder: b.folder } : {}) }; startJob(job, { url: decrypt(t.connection_encrypted) }); return send(res, 202, { job }); }
  if (req.method === 'GET' && req.url.startsWith('/api/jobs/')) { const j = jobs.get(req.url.split('/').pop()); return j ? send(res, 200, { job: j }) : send(res, 404, { error: 'Job not found' }); }
  return send(res, 404, { error: 'Not found' });
} catch (e) { console.error(e); if (!res.headersSent) return send(res, 500, { error: 'Internal server error' }); res.destroy(); } });
migrate().then(bootstrapProject).then(() => server.listen(PORT, HOST, () => console.log(`Supabase VaultManager listening on ${HOST}:${PORT}`))).catch(error => { console.error('Control database migration failed:', error); process.exit(1); });
