const http = require('node:http');
const fs = require('node:fs');
const path = require('node:path');
const crypto = require('node:crypto');
const { spawn } = require('node:child_process');
const bcrypt = require('bcryptjs');

const PORT = Number(process.env.PORT || 3000), HOST = process.env.HOST || '0.0.0.0';
const DATA_DIR = process.env.DATA_DIR || path.join(__dirname, 'data');
const BACKUP_DIR = process.env.BACKUP_DIR || path.join(DATA_DIR, 'backups');
const COOKIE = 'vault_session', MAX_BODY = 1024 * 1024;
const secureCookie = process.env.COOKIE_SECURE ? process.env.COOKIE_SECURE === 'true' : process.env.NODE_ENV === 'production';
const storageMode = (process.env.BACKUP_STORAGE || 'local').toLowerCase();
const sessions = new Map(), jobs = new Map(), loginAttempts = new Map();
let jobRunning = false;
for (const dir of [DATA_DIR, BACKUP_DIR]) fs.mkdirSync(dir, { recursive: true, mode: 0o700 });
for (const key of ['ADMIN_USERNAME', 'APP_ENCRYPTION_KEY']) if (!process.env[key]) throw new Error(`${key} is required`);
if (!process.env.ADMIN_PASSWORD_HASH && !process.env.ADMIN_PASSWORD_HASH_B64) throw new Error('ADMIN_PASSWORD_HASH_B64 is required');
if (!['local', 's3'].includes(storageMode)) throw new Error('BACKUP_STORAGE must be local or s3');
if (storageMode === 's3' && (!process.env.S3_BUCKET || !process.env.S3_REGION)) throw new Error('S3_BUCKET and S3_REGION are required for S3 storage');
const encryptionKey = crypto.createHash('sha256').update(process.env.APP_ENCRYPTION_KEY).digest();

function readJson(file, fallback) { try { return JSON.parse(fs.readFileSync(file, 'utf8')); } catch { return fallback; } }
function writeJson(file, value) { const tmp = `${file}.tmp`; fs.writeFileSync(tmp, JSON.stringify(value, null, 2), { mode: 0o600 }); fs.renameSync(tmp, file); }
function vault() { const v = readJson(path.join(DATA_DIR, 'vault.json'), { targets: [] }); return Array.isArray(v.targets) ? v : { targets: [] }; }
function history() { const h = readJson(path.join(DATA_DIR, 'history.json'), []); return Array.isArray(h) ? h : []; }
function saveHistory(entry) { const h = history().filter(x => x.id !== entry.id); h.push(entry); writeJson(path.join(DATA_DIR, 'history.json'), h.slice(-500)); }
function encrypt(value) { const iv = crypto.randomBytes(12), c = crypto.createCipheriv('aes-256-gcm', encryptionKey, iv); const data = Buffer.concat([c.update(value, 'utf8'), c.final()]); return [iv, c.getAuthTag(), data].map(x => x.toString('base64')).join('.'); }
function decrypt(value) { const [iv, tag, data] = value.split('.'), d = crypto.createDecipheriv('aes-256-gcm', encryptionKey, Buffer.from(iv, 'base64')); d.setAuthTag(Buffer.from(tag, 'base64')); return Buffer.concat([d.update(Buffer.from(data, 'base64')), d.final()]).toString('utf8'); }
function verifyPassword(password) { const stored = process.env.ADMIN_PASSWORD_HASH_B64 ? Buffer.from(process.env.ADMIN_PASSWORD_HASH_B64, 'base64').toString('utf8') : String(process.env.ADMIN_PASSWORD_HASH); if (/^\$2[aby]?\$\d{2}\$/.test(stored)) return bcrypt.compareSync(password, stored); const separator = stored.includes(':') ? ':' : '$', [salt, digest] = stored.split(separator); if (!salt || !/^[a-f0-9]{128}$/i.test(digest)) return false; const actual = crypto.scryptSync(password, salt, 64).toString('hex'); return crypto.timingSafeEqual(Buffer.from(actual, 'hex'), Buffer.from(digest, 'hex')); }
function parseCookies(req) { return Object.fromEntries((req.headers.cookie || '').split(';').filter(Boolean).map(x => { const i = x.indexOf('='); return [x.slice(0, i).trim(), decodeURIComponent(x.slice(i + 1))]; })); }
function auth(req) { const token = parseCookies(req).vault_session, s = token && sessions.get(token); return s && s.expires > Date.now() ? { token, ...s } : null; }
function send(res, status, value, headers = {}) { res.writeHead(status, { 'Content-Type': 'application/json; charset=utf-8', 'Cache-Control': 'no-store', ...headers }); res.end(JSON.stringify(value)); }
function staticFile(res, name, type) { const content = fs.readFileSync(path.join(__dirname, 'public', name)); res.writeHead(200, { 'Content-Type': type, 'Cache-Control': 'no-store' }); res.end(content); }
function readBody(req) { return new Promise((resolve, reject) => { let raw = ''; req.on('data', c => { raw += c; if (raw.length > MAX_BODY) { reject(new Error('Request too large')); req.destroy(); } }); req.on('end', () => { try { resolve(raw ? JSON.parse(raw) : {}); } catch { reject(new Error('Invalid JSON')); } }); req.on('error', reject); }); }
function validName(v) { return typeof v === 'string' && /^[A-Za-z0-9_-]{1,48}$/.test(v); }
function validUrl(v) { try { const u = new URL(v); return ['postgres:', 'postgresql:'].includes(u.protocol) && u.hostname && u.pathname === '/postgres'; } catch { return false; } }
function safeFolder(v) { return typeof v === 'string' && /^[0-9TZ_.-]{10,64}$/.test(v); }
function csrf(req, session) { try { return req.headers['x-csrf-token'] === session.csrf && req.headers.origin && new URL(req.headers.origin).host === req.headers.host; } catch { return false; } }
function redacted(text) { return String(text).replace(/postgres(?:ql)?:\/\/[^\s]+/gi, '[redacted-url]'); }
function command(bin, args, job, cwd) { return new Promise((resolve, reject) => { const env = { ...process.env }; delete env.PGPASSWORD; const child = spawn(bin, args, { cwd, env, stdio: ['ignore', 'pipe', 'pipe'] }); let stderr = ''; child.stdout.on('data', d => job.log += redacted(d)); child.stderr.on('data', d => { stderr += d; job.log += redacted(d); }); child.on('error', reject); child.on('close', code => code === 0 ? resolve() : reject(new Error(`${bin} exited with code ${code}: ${redacted(stderr).slice(-500)}`))); }); }
function capture(bin, args, cwd) { return new Promise((resolve, reject) => { const child = spawn(bin, args, { cwd, env: process.env, stdio: ['ignore', 'pipe', 'pipe'] }); let out = '', err = ''; child.stdout.on('data', d => out += d); child.stderr.on('data', d => err += d); child.on('error', reject); child.on('close', code => code === 0 ? resolve(out) : reject(new Error(`${bin} exited with code ${code}: ${err.slice(-300)}`))); }); }
async function archiveFolder(name) { const archive = path.join(DATA_DIR, `${name}.tar.gz`); await command('tar', ['-czf', archive, '-C', BACKUP_DIR, name], { log: '' }, DATA_DIR); return archive; }
async function uploadS3(archive, name) { const key = `${process.env.S3_PREFIX || 'vaultmanager'}/${name}.tar.gz`; await command('aws', ['s3', 'cp', archive, `s3://${process.env.S3_BUCKET}/${key}`, '--region', process.env.S3_REGION, '--only-show-errors'], { log: '' }, DATA_DIR); return key; }
async function signS3(key) { return (await capture('aws', ['s3', 'presign', `s3://${process.env.S3_BUCKET}/${key}`, '--region', process.env.S3_REGION, '--expires-in', '900'], DATA_DIR)).trim(); }
function publicTargets() { return vault().targets.map(({ id, name, createdAt }) => ({ id, name, createdAt })); }
async function runBackup(target, job) { const name = new Date().toISOString().replace(/[:.]/g, '-'); const folder = path.join(BACKUP_DIR, name); fs.mkdirSync(folder, { recursive: true, mode: 0o700 }); job.folder = name; for (const [label, args] of [['roles.sql', ['db', 'dump', '--db-url', target.url, '-f', 'roles.sql', '--role-only']], ['schema.sql', ['db', 'dump', '--db-url', target.url, '-f', 'schema.sql']], ['data.sql', ['db', 'dump', '--db-url', target.url, '-f', 'data.sql', '--data-only', '--use-copy']]]) { job.log += `Running ${label}...\n`; await command('supabase', args, job, folder); } const archive = await archiveFolder(name); if (storageMode === 's3') { job.storageKey = await uploadS3(archive, name); fs.rmSync(archive, { force: true }); } job.status = 'succeeded'; job.finishedAt = new Date().toISOString(); saveHistory({ id: job.id, type: 'backup', targetId: job.targetId, folder: name, status: job.status, startedAt: job.startedAt, finishedAt: job.finishedAt, storage: storageMode, storageKey: job.storageKey || null }); }
async function runRestore(target, job) { let folder = path.join(BACKUP_DIR, job.folder); if (!fs.existsSync(folder) && storageMode === 's3') { const source = history().find(x => x.folder === job.folder && x.type === 'backup' && x.storageKey); if (!source) throw new Error('Backup folder not found'); const archive = path.join(DATA_DIR, `${job.folder}.tar.gz`); await command('aws', ['s3', 'cp', `s3://${process.env.S3_BUCKET}/${source.storageKey}`, archive, '--only-show-errors'], job, DATA_DIR); await command('tar', ['-xzf', archive, '-C', BACKUP_DIR], job, DATA_DIR); fs.rmSync(archive, { force: true }); } if (!fs.existsSync(folder)) throw new Error('Backup folder not found'); for (const [label, args] of [['roles.sql', ['-v', 'ON_ERROR_STOP=1', '--single-transaction', target.url, '-f', 'roles.sql']], ['schema.sql', ['-v', 'ON_ERROR_STOP=1', '--single-transaction', target.url, '-f', 'schema.sql']], ['data.sql', ['-v', 'ON_ERROR_STOP=1', '--single-transaction', target.url, '-c', "SET session_replication_role = 'replica';", '-f', 'data.sql']]]) { job.log += `Restoring ${label}...\n`; await command('psql', args, job, folder); } job.status = 'succeeded'; job.finishedAt = new Date().toISOString(); saveHistory({ id: job.id, type: 'restore', targetId: job.targetId, folder: job.folder, status: job.status, startedAt: job.startedAt, finishedAt: job.finishedAt, storage: storageMode }); }
function startJob(job, target) { jobs.set(job.id, job); (async () => { while (jobRunning) await new Promise(r => setTimeout(r, 500)); jobRunning = true; job.status = 'running'; job.log = `Started ${job.type} job ${job.id}\n`; try { await (job.type === 'backup' ? runBackup(target, job) : runRestore(target, job)); job.log += `${job.type} completed successfully.\n`; } catch (e) { job.status = 'failed'; job.error = e.message; job.finishedAt = new Date().toISOString(); job.log += `FAILED: ${e.message}\n`; if (job.type === 'backup') saveHistory({ id: job.id, type: 'backup', targetId: job.targetId, folder: job.folder || null, status: 'failed', startedAt: job.startedAt, finishedAt: job.finishedAt, storage: storageMode }); } finally { jobRunning = false; } })(); }
function cronFieldMatches(field, value, min, max) { return field.split(',').some(part => { const [range, stepText] = part.split('/'), step = Number(stepText || 1); if (!Number.isInteger(step) || step < 1) return false; if (range === '*') return value >= min && value <= max && (value - min) % step === 0; const [a, b = a] = range.split('-').map(Number); return Number.isInteger(a) && Number.isInteger(b) && a >= min && b <= max && value >= a && value <= b && (value - a) % step === 0; }); }
function cronMatches(date, expression) { const p = String(expression || '').trim().split(/\s+/), v = [date.getMinutes(), date.getHours(), date.getDate(), date.getMonth() + 1, date.getDay()], ranges = [[0, 59], [0, 23], [1, 31], [1, 12], [0, 6]]; return p.length === 5 && p.every((x, i) => cronFieldMatches(x, v[i], ...ranges[i])); }
function cronTick() { if (!process.env.BACKUP_CRON || !process.env.CRON_TARGET_ID || !cronMatches(new Date(), process.env.BACKUP_CRON) || [...jobs.values()].some(j => j.scheduled && j.status === 'running')) return; const t = vault().targets.find(x => x.id === process.env.CRON_TARGET_ID); if (!t) return console.error('CRON_TARGET_ID does not match a target'); startJob({ id: crypto.randomUUID(), type: 'backup', targetId: t.id, status: 'queued', startedAt: new Date().toISOString(), scheduled: true }, { url: decrypt(t.connection) }); }
setInterval(cronTick, 60000).unref();

const server = http.createServer(async (req, res) => { try {
  if (req.method === 'GET' && req.url === '/') return staticFile(res, 'index.html', 'text/html; charset=utf-8');
  if (req.method === 'GET' && req.url === '/app.js') return staticFile(res, 'app.js', 'application/javascript');
  if (req.method === 'GET' && req.url === '/styles.css') return staticFile(res, 'styles.css', 'text/css');
  if (req.method === 'POST' && req.url === '/api/login') { const ip = req.socket.remoteAddress || 'unknown', a = loginAttempts.get(ip) || { count: 0, reset: Date.now() + 60000 }; if (a.reset < Date.now()) { a.count = 0; a.reset = Date.now() + 60000; } if (a.count >= 10) return send(res, 429, { error: 'Too many attempts. Try again shortly.' }); const b = await readBody(req); if (b.username !== process.env.ADMIN_USERNAME || !verifyPassword(b.password || '')) { a.count++; loginAttempts.set(ip, a); return send(res, 401, { error: 'Invalid credentials' }); } const token = crypto.randomBytes(32).toString('hex'); sessions.set(token, { csrf: crypto.randomBytes(24).toString('hex'), expires: Date.now() + 8 * 3600e3 }); return send(res, 200, { ok: true }, { 'Set-Cookie': `${COOKIE}=${token}; HttpOnly; ${secureCookie ? 'Secure; ' : ''}SameSite=Strict; Path=/; Max-Age=28800` }); }
  const session = auth(req); if (!session) return send(res, 401, { error: 'Authentication required' });
  if (req.method === 'POST' && req.url === '/api/logout') { sessions.delete(session.token); return send(res, 200, { ok: true }, { 'Set-Cookie': `${COOKIE}=; HttpOnly; ${secureCookie ? 'Secure; ' : ''}SameSite=Strict; Path=/; Max-Age=0` }); }
  if (req.method === 'GET' && req.url === '/api/session') return send(res, 200, { username: process.env.ADMIN_USERNAME, csrf: session.csrf, targets: publicTargets(), jobs: [...jobs.values()].slice(-50), history: history().slice(-50).reverse(), storage: storageMode, cron: process.env.BACKUP_CRON || null });
  if (req.method === 'GET' && req.url === '/api/backups') return send(res, 200, { backups: history().filter(x => x.type === 'backup').slice(-100).reverse() });
  if (req.method === 'GET' && req.url.startsWith('/api/backups/') && req.url.endsWith('/download')) { const name = req.url.split('/')[3]; if (!safeFolder(name)) return send(res, 400, { error: 'Invalid backup name' }); const h = history().find(x => x.folder === name && x.type === 'backup' && x.status === 'succeeded'); if (!h) return send(res, 404, { error: 'Backup not found' }); if (storageMode === 's3') return res.writeHead(302, { Location: await signS3(h.storageKey) }).end(); const archive = await archiveFolder(name); res.writeHead(200, { 'Content-Type': 'application/gzip', 'Content-Disposition': `attachment; filename="${name}.tar.gz"`, 'Content-Length': fs.statSync(archive).size }); fs.createReadStream(archive).pipe(res).on('finish', () => fs.rmSync(archive, { force: true })); return; }
  if (!csrf(req, session)) return send(res, 403, { error: 'CSRF validation failed' });
  if (req.method === 'POST' && req.url === '/api/targets') { const b = await readBody(req); if (!validName(b.name) || !validUrl(b.connectionString)) return send(res, 400, { error: 'Use a simple name and a valid PostgreSQL URL ending in /postgres.' }); const v = vault(); v.targets.push({ id: crypto.randomUUID(), name: b.name, connection: encrypt(b.connectionString), createdAt: new Date().toISOString() }); writeJson(path.join(DATA_DIR, 'vault.json'), v); return send(res, 201, { targets: publicTargets() }); }
  if (req.method === 'DELETE' && req.url.startsWith('/api/targets/')) { const id = req.url.split('/').pop(), v = vault(); v.targets = v.targets.filter(t => t.id !== id); writeJson(path.join(DATA_DIR, 'vault.json'), v); return send(res, 200, { targets: publicTargets() }); }
  if (req.method === 'POST' && (req.url.startsWith('/api/backup/') || req.url === '/api/restore')) { const b = await readBody(req), targetId = b.targetId || req.url.split('/').pop(), t = vault().targets.find(x => x.id === targetId), type = req.url === '/api/restore' ? 'restore' : 'backup'; if (!t) return send(res, 404, { error: 'Target not found' }); if (type === 'restore' && (!safeFolder(b.folder) || b.confirm !== 'RESTORE')) return send(res, 400, { error: 'Enter a valid backup folder and type RESTORE to confirm.' }); const job = { id: crypto.randomUUID(), type, targetId: t.id, status: 'queued', startedAt: new Date().toISOString(), ...(type === 'restore' ? { folder: b.folder } : {}) }; startJob(job, { url: decrypt(t.connection) }); return send(res, 202, { job }); }
  if (req.method === 'GET' && req.url.startsWith('/api/jobs/')) { const j = jobs.get(req.url.split('/').pop()); return j ? send(res, 200, { job: j }) : send(res, 404, { error: 'Job not found' }); }
  return send(res, 404, { error: 'Not found' });
} catch (e) { console.error(e); if (!res.headersSent) return send(res, 500, { error: 'Internal server error' }); res.destroy(); } });
server.listen(PORT, HOST, () => console.log(`Supabase VaultManager listening on ${HOST}:${PORT}`));
